version: '4.30.0'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: 'zookeeper-sport-planner'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: 'kafka-sport-planner'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:13.6
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=planner

  clinic-application:
    container_name: clinic-application
    build:
      dockerfile: Clinic/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/planner
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8091:8091"
    depends_on:
      - postgres

  journaling-application:
    container_name: journaling-application
    build:
      dockerfile: Journaling/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/planner
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - spring.kafka.bootstrap-servers=broker:9092
      - spring.kafka.producer.bootstrap-servers=broker:9092
    depends_on:
      - kafka
      - zookeeper
      - postgres

  planner-application:
    container_name: planner-application
    build:
      dockerfile: Planner/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/planner
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - spring.kafka.bootstrap-servers=broker:9092
      - spring.kafka.producer.bootstrap-servers=broker:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
      - postgres