spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres # default
    password: password # default

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: "classpath:schema.sql"
#      data-locations: "classpath:data.sql"
