spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clinic
    username: postgres # default
    password: password # default
  application:
    name: "clinic-application"
  sql:
    init:
      mode: always
      data-locations: "classpath:data.sql"
      schema-locations: "classpath:schema.sql"
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update


server:
  port: 8091

