spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres # default
    password: password # default
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      schema-locations: "classpath:schema.sql"

server:
  port: 8091

