spring:
  kafka:
    consumer:
      group-id: 'groupKafka'
      bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres # default
    password: password # default
  sql:
    init:
      mode: always
      schema-locations: "classpath:schema.sql"

server:
  port: 8090

